### ISSUE TITLE
possible typo?

### ISSUE THREAD

**Issue by USBMenus** [sch-lda/SCH-LUA-YIMMENU#14]
is this a typo because i dont see a definition for it anywhere?

https://github.com/sch-lda/SCH-LUA-YIMMENU/blob/eba547bc22511922ee0296d19d058c6fa4dc0bf1/sch.lua#L87

**Comment by sch-lda** [comment]
local_() is just randomly typed. I was told that this prevents this lua from loading on certain p2c menus that skid yim's lua support. but since I didn't do any obfuscation, here's a couple of lines of deprecated code.

**Comment by USBMenus** [comment]
oh ok, cool
