### ISSUE TITLE
how does gifting vehicles work?

### ISSUE THREAD

**Issue by USBMenus** [sch-lda/SCH-LUA-YIMMENU#5]
i was trying to use gift opressor mk2 and even tried to uncomment the deluxo code and use that but it didnt work either, are they not working or it there something i need to do for it to work?

**Comment by sch-lda** [comment]
replace "while STREAMING.HAS_MODEL_LOADED(joaat("oppressor2")) ~= 1 do " with "while not STREAMING.HAS_MODEL_LOADED(joaat("oppressor2")) do"
