### ISSUE TITLE
[request] add a follow player option

### ISSUE THREAD

**Issue by USBMenus** [sch-lda/SCH-LUA-YIMMENU#8]
this will let the user follow the selected player by teleporting them on top of the player
add this somewhere in the network tab
```
local followPlayer = gui.get_tab(""):add_checkbox("Follow Player")
```
i added this in the schlua-defpservice registered loop, maybe it should be somewhere else?
```
        if  followPlayer:is_enabled() then
            local targpos = ENTITY.GET_ENTITY_COORDS(PLAYER.GET_PLAYER_PED(network.get_selected_player()), false)
            PED.SET_PED_COORDS_KEEP_VEHICLE(PLAYER.PLAYER_PED_ID(), targpos.x, targpos.y, targpos.z + 1)
        end
```

**Comment by sch-lda** [comment]
![image](https://github.com/sch-lda/SCH-LUA-YIMMENU/assets/54973190/b35533a7-50f5-4947-8a30-6a2c3511c21d)
One regular way (considering distance) and one aggressive way."
